Changes made to make scripts better
BSVN/ScalableProductionReadyServiceSample pull request #1
Opened 2023-05-30 06:18 UTC by meghasemim1999

2023-06-08 17:49 UTC, soroshsabz requested changes

2023-06-08 17:49 UTC, soroshsabz commented on Deployment/Kubernetes/install-kubeadm.sh
> +	sudo curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
why remove flags of curl?

2023-06-08 17:49 UTC, soroshsabz commented on Deployment/Kubernetes/install-kubeadm.sh
> -	echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
I do not know, why this change is useful?

2023-06-08 17:49 UTC, soroshsabz commented on Deployment/Kubernetes/install-kubeadm.sh
> -	sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
I suggest, in first stage download gpg key, and then add this key, if you want, with sudo `apt-key add`

2023-06-15 09:58 UTC, soroshsabz requested changes

2023-06-15 09:58 UTC, soroshsabz commented on Deployment/Kubernetes/install-kubeadm.sh
> -	sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
Why does not save this key in /usr/share/keyrings/kubernetes-archive-keyring.gpg ?

2023-06-15 09:58 UTC, soroshsabz commented on Deployment/Kubernetes/install-kubeadm.sh
> +	sudo apt-key add apt-key.gpg
why add system wide?

2023-06-15 09:58 UTC, soroshsabz commented on Deployment/Kubernetes/install-kubeadm.sh
> -	echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
please response it

2023-06-15 11:12 UTC, meghasemim1999 commented
all unneccessary changes are removed.

@soroshsabz

2023-06-15 12:33 UTC, soroshsabz approved these changes

2023-06-15 12:34 UTC, merged